services:
    api:
        build:
            context: ./docker/php
        container_name: lead_management_api
        volumes:
            - .:/var/www
        working_dir: /var/www
        depends_on:
            - db
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: lead_management_nginx_web
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - api
        networks:
            - laravel

    db:
        image: postgres:16-alpine
        container_name: lead_management_db
        restart: always
        environment:
            POSTGRES_DB: lead_management
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    pg_data:
